### ISSUE TITLE
GUI weirdness (Ubuntu)

### ISSUE THREAD

**Issue by repsorp** [Max-Coin/maxcoin#49]
Why is the icon tray on the left side when it used to be on the right side (like Vericoin and Startcoin icons on the image) ?
![icontray](https://cloud.githubusercontent.com/assets/6297032/4179492/c121d738-36c8-11e4-8fc7-0874c424e319.png)

**Comment by goombaloon** [comment]
Looks like this works as expected with v0.9.4 on Ubuntu 16.04, but is still an issue on Ubuntu 14.04.
