### ISSUE TITLE
Compile errors with Qt

### ISSUE THREAD

**Issue by Alkaris** [Max-Coin/maxcoin#50]
I cannot seem compile from source with maxcoin-qt.pro, I have everything I needed installed I have Qt4 and Qt5 as well as all their library development files for Linux Mint 16, and it hits an error in QtCreator. I made check that I had all the required tools for Qt4

![shutter_2014_09_16__01 59 07](https://cloud.githubusercontent.com/assets/6682988/4274153/5e4450b2-3cf1-11e4-93d9-ccc2056bb7c2.png)

an odd encounter I noticed when I opened this up in QtCreator is that that I see yellow triangle exclamation marks next to the qt4 library directory it points to for the project, not sure if that has anything to do with it.

**Comment by goombaloon** [comment]
Please try v0.9.4 and see if this is still a problem.  If so, please follow the revised instructions at [https://github.com/Max-Coin/maxcoin/blob/master/doc/build-linux.md](url) and let us know if it's still a problem.
