### ISSUE TITLE
Timewarp vulnerability

### ISSUE THREAD

**Issue by reorder** [Max-Coin/maxcoin#51]
A simulation I have made for another coin (and actually DGW variants but that should not matter) has shown that clamping PastRateActualSeconds to non-negative range at https://github.com/Max-Coin/maxcoin/blob/master/src/main.cpp#L1257 actually worsens block times distribution under timewarp attack, instead of improving it.

With randomized nTime modification average blocktime over long run was reduced to just 60% of its target, and I assume targeted modification could achieve even more. This is quite an incentive for an attacker with sheer hashpower. I think this is what actually happened during recent major blockchain hickups.

My (sketchy and dirty) simulation code is here: https://gist.github.com/reorder/be3d680edd467d8cffc4

**Comment by goombaloon** [comment]
Thanks for the information!  I'll take a look.  I know this post is a few years old, but would you be interested in submitting a pull request with the suggested revisions?  Thanks!

**Comment by reorder** [comment]
Sorry, I cannot dig it further on the moment, moreover, a PR would include decision on a hardfork which is obviously not an outside job. What I'd suggest to do is to make a similar montecarlo simulation for Maxcoin difficulty adjustment algorithm, assuming someone malicious **does** actively fiddle with blocks nTime to maximize his yield and/or attack the network, then you can quantify possible effects and adjust the algorithm. My only find is that clamping PastRateActualSeconds to be >= 1 may only worsen the outcome in similar algorithm.
