### ISSUE TITLE
maxcoin-installer.exe blocked by avast as malware

### ISSUE THREAD

**Issue by morris69** [Max-Coin/maxcoin#55]
Hi,
I have maxcoin wallet V8.9 but it states no block source available.  I have Win 10 with Avast V17.8.  When I download maxcoin-installer.exe V9.4.0, Avast will block the file on three occasions with malware warning.  can you advice how I can upgrade maxcoin wallet.

**Comment by MxJmpBean** [comment]
Sorry no one replied to this. There is a new release of the wallet, but some antiviruses still detect it as unwanted software due to the mining code inside of it.

**Comment by buckshee** [comment]
please try the latest installer or add an exception to your AV software
