### ISSUE TITLE
hi , plz how I can solve this problem 

### ISSUE THREAD

**Issue by ayoubGL** [Max-Coin/maxcoin#58]
13:40:23: Running steps for project Projet_TDM...
13:40:23: Configuration unchanged, skipping qmake step.
13:40:23: Starting: "/usr/bin/make"
g++ -c -pipe -g -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x000000` -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../Projet_TDM -I. -isystem /usr/local/include/opencv2 -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o mainwindow.o ../Projet_TDM/mainwindow.cpp
/bin/sh: -c: line 0: unexpected EOF while looking for matching ``'
/bin/sh: -c: line 1: syntax error: unexpected end of file
make: *** [Makefile:722: mainwindow.o] Error 1
13:40:23: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project Projet_TDM (kit: Desktop)
The kit Desktop has configuration issues which might be the root cause for this problem.
When executing step "Make"
13:40:23: Elapsed time: 00:00.

**Comment by MxJmpBean** [comment]
Are you trying to compile the Qt wallet?

**Comment by buckshee** [comment]
Current version only builds simply on Ubuntu 16.04

**Comment by atomminer** [comment]
so it does on clean 17.04, 17.10 and 18.04
