### ISSUE TITLE
scriptsig first block difficulty  copy-pasted from bitcoin source

### ISSUE THREAD

**Issue by alexeyneu** [Max-Coin/maxcoin#59]
`486604799`  
https://github.com/Max-Coin/maxcoin/blob/2d6f3e77a009b0667418951469d66aa86f96b06a/src/main.cpp#L2914

**Comment by atomminer** [comment]
so what's the issue?

**Comment by alexeyneu** [comment]
there's no reason for this . it goes as first block difficulty when it's used . for sure it doesnt

**Comment by buckshee** [comment]
my understanding is that most of the stuff with CBigNum is replaced in later bitcoin-core versions, but even with that please fork and test your ideas

**Comment by alexeyneu** [comment]
it's not bignum related. Most of(but not all) other altcoins has it too. just a sign of that that this part of code is blindly copypasted. to change it now you'll need to relaunch blockchain (means replace this coin with a new one)

**Comment by buckshee** [comment]
related, please take your stupidity elsewhere - copy and paste? you mean fork

**Comment by alexeyneu** [comment]
https://github.com/alexeyneu/BlockZero/blob/d77ebec362c68ee3061c077b8a74783428df99cc/BlockZero.cpp#L60
https://github.com/alexeyneu/BlockZero/blob/d77ebec362c68ee3061c077b8a74783428df99cc/BlockZero.cpp#L71
https://github.com/alexeyneu/BlockZero/blob/d77ebec362c68ee3061c077b8a74783428df99cc/BlockZero.cpp#L72  
fuck you

**Comment by buckshee** [comment]
do something useful, change your tone, or shut up - nobody is saying 0.8 based stuff is perfect!
