### ISSUE TITLE
g++: Error

### ISSUE THREAD

**Issue by shugevara** [Max-Coin/maxcoin#60]
I have carried out the instructions in the build section to clone maxcoin. However it finished with this error

"g++: error: /usr/lib/x86_64-linux-gnu/libminiupnpc.a: No such file or directory
makefile.unix:197: recipe for target 'maxcoind' failed"

Building on 32 bit Ubuntu 16.04

ANyone any ideas?

**Comment by atomminer** [comment]
$ sudo apt install miniupnpc
or disable upnpc support in the config script like this:
$ qmake "USE_UPNP=0"

**Comment by shugevara** [comment]
Thanks for your help
