### ISSUE TITLE
linux_wallet_x64.deb cannot start

### ISSUE THREAD

**Issue by Abdula-2015** [Max-Coin/maxcoin#61]
1) **linux_wallet_x64.deb cannot start**

$maxcoin-qt 
maxcoin-qt: error while loading shared libraries: **libssl.so.1.0.0**: cannot open shared object file: No such file or directory

2) On the desktop did not appear a shortcut of this Wallet

OS: Debian 9/64

**Comment by Abdula-2015** [comment]
Why does no one answer? So the project is in a state of stagnation??

**Comment by decentralizeduser** [comment]
Hi Abdula, I hope you realised you only posted your comment/issue only 22 hours ago, and we are busy working on other projects, and we may not get to requests as soon as you are expecting.

Thanks for letting us know your issue, we will look into it

**Comment by atomminer** [comment]
sudo apt install libssl1.0.0

**Comment by Abdula-2015** [comment]
1) ```
sudo apt install libssl1.0.0
The libssl1.0.0 package is not available,
```
2) So this is a bad method.
**libssl1.0.0** must be put inside **linux_wallet_x64.deb** so as not to search for it

**Comment by Abdula-2015** [comment]
**libssl1.0.2** I have installed originally (**libssl1.1** too).

Alas, it does not help :(

**Comment by atomminer** [comment]
give me some more info so I can help...
here's what I have on my laptop:
$ dpkg -l | grep libssl
ii  libssl-dev:amd64                                            1.0.2g-1ubuntu13.5 

and everything works well. what's your output of 
$sudo apt-cache search libssl

did you try 'make clean' then 'make' after updating the ssl deps? 
what errors are you getting? I don't know configuration of your OS so I can only help if you show me what's failing...and which libs you have installed.

**Comment by Abdula-2015** [comment]
Please,

```
$ dpkg -l | grep libssl
ii  libssl1.0.2:amd64                      1.0.2l-2+deb9u3                      amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64                        1.1.0f-3+deb9u2                      amd64        Secure Sockets Layer toolkit - shared libraries

```
```
$sudo apt-cache search libssl
libssl1.0.2 - инструментарий Secure Sockets Layer — разделяемые библиотеки
libssl1.1 - инструментарий Secure Sockets Layer — разделяемые библиотеки
cl-plus-ssl - Common Lisp interface to OpenSSL
dcmtk - OFFIS DICOM toolkit command line utilities
libdcmtk-dev - OFFIS DICOM toolkit development libraries and headers
libdcmtk8 - OFFIS DICOM toolkit runtime libraries
libssl-ocaml - OCaml bindings for OpenSSL (runtime)
libssl-ocaml-dev - OCaml bindings for OpenSSL
libssl-dev - Secure Sockets Layer toolkit - development files
libssl-doc - Secure Sockets Layer toolkit - development documentation
libssl1.0-dev - Secure Sockets Layer toolkit - development files
perl-openssl-defaults - version compatibility baseline for Perl OpenSSL packages
r-cran-openssl - GNU R toolkit for encryption, signatures and certificates based on OpenSSL
```
"**make clean**," then "make" I did not. Because I do not know what it's need for and how to do it.

**Comment by Abdula-2015** [comment]
Developers, do not you want to help solve the problem? Well, I'll have to remove your stupid wallet.

**Comment by atomminer** [comment]
default libssl location: /lib/x86_64-linux-gnu/libssl.so.1.0.0
libssl1.0.0 is available as a default package on your OS: https://packages.debian.org/search?keywords=libssl1.0.0
in case you installed libssl into custom location, please make symlink to it from default expected location.

manual install can be done by getting it from https://packages.debian.org/jessie/libssl1.0.0 and install like dpkg --install libssl1.0.0_1.0.1t-+deb8u6_amd64.deb as root

**Comment by buckshee** [comment]
we now have some AppImages, even for rude people
