### ISSUE TITLE
Error in documentation (wiki) regarding merkle tree calculation

### ISSUE THREAD

**Issue by skoroneos** [Max-Coin/maxcoin#63]
In wiki Hashing-Conventions
https://github.com/Max-Coin/maxcoin/wiki/Hashing-Conventions
there is an error in documentation regarding the Merkle tree calculation as it states it's using double sha256 while it actually uses single sha256
This is also referenced here
https://github.com/Max-Coin/maxcoin/issues/40.

I verified this also in code

**Comment by atomminer** [comment]
wiki has been updated. Thanks for the input!
