### ISSUE TITLE
 about address and transaction generation

### ISSUE THREAD

**Issue by leegod** [Max-Coin/maxcoin#64]
We have been trying to generate address + privateKey pair compatible with xxxcoin(maxcoin cloned coin) (using secp256r1 instead of `secp256k1`) and using your prefix (PUBKEY_ADDRESS = 50).
Here is the example of the address that we’ve got: MMyevnCKFexH8785tWVveFxyiE9YqMjGMX.
Unfortunately mircoin client replies as Invalid MirCoin address

we are using bitcoinjs-lib to generate addresses (to be precise - this version `bitcoinjs-lib-secp256r1`).

Have you ever succeded with offline address generation and offline transaction generation using any programming language?

if some one knows about address and transaction generation (like in browser - https://coinb.in) please?. Maybe someone has is a code example

**Comment by atomminer** [comment]
here's the project that does wallet generation correctly: https://github.com/Max-Coin/paper-wallet-generator

unfortunately, there's no project like coinbin for MaxCoin yet. If you're willing to fork coinbin and make it to work with MaxCoin, feel free to do so and please share your experience with the community!

**Comment by buckshee** [comment]
inactive, closing
