### ISSUE TITLE
make error share/genbuild.sh

### ISSUE THREAD

**Issue by ppTcheB** [Max-Coin/maxcoin#65]
I was getting permission denied errors regarding build_detect_platform. This can be fixed with a simple.

chmod 755 src/leveldb/build_detect_platform

The same with src/secp256k1/autogen.sh

Now I think that a file is missing, error : 

make[1] : on quitte le répertoire « /Bytepay/src/secp256k1 »
cd /Bytepay; /bin/sh share/genbuild.sh /Bytepay/build/build.h
/bin/sh: 0: Can't open share/genbuild.sh

Cordialy.

**Comment by atomminer** [comment]
leveldb/build_detect_platform has valid +x permission on Ubuntu

there's no src/secp256k1 folder at all. You should talk to Bytepay (whatever it is) to find out why does it have building problems.
