### ISSUE TITLE
“MaxCoin-QT” is damaged and can’t be opened. on Mac

### ISSUE THREAD

**Issue by teshy** [Max-Coin/maxcoin#68]
I downloaded the latest release v0.9.4.2, on Mac OS X 10.13.6. 
“MaxCoin-QT” is damaged and can’t be opened. You should move it to the Trash.

Can you provide an updated build please?

**Comment by decentralizeduser** [comment]
I have the same OS and it works fine on mine.  Someone else on the maxcoin telegram chat mentioned the same thing on 10.13.6 .. the download may be currupt, can you try downloading again and seeing if you have the same problem?  I have not been able to replicate this issue.

**Comment by buckshee** [comment]
inactive, closing
