### ISSUE TITLE
Compile error wake.cpp unsigned int

### ISSUE THREAD

**Issue by Ur-Quan** [Max-Coin/maxcoin#69]
Compiling the latest src on ubuntu. Errors:

`wake.cpp: In member function ‘void CryptoPP::WAKE_Base::GenKey(CryptoPP::word32, CryptoPP::word32, CryptoPP::word32, CryptoPP::word32)’:`
`wake.cpp:34:15: error: narrowing conversion of ‘3868867420’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
   0x9ee27cf3, } ;`
`wake.cpp:34:15: error: narrowing conversion of ‘3553042405’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]`
`wake.cpp:34:15: error: narrowing conversion of ‘2872865746’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]`
`wake.cpp:34:15: error: narrowing conversion of ‘2665643251’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]`

I think [this](https://github.com/weidai11/cryptopp/commit/44015c26ba215f955b1e653f9c8f3c894a532707) is the fix. After that compiled successfully, did not test yet.

**Comment by daygle** [comment]
This fix worked for me :)

**Comment by buckshee** [comment]
Thanks for the research and confirm, external crptopp is the goal but we'll keep changing the bundled versions until that happens.

**Comment by buckshee** [comment]
this was fixed, but there seems to have been an issue with the commits
